field: 1cb1883a-4c9d-4d32-9386-210a71fbe719 # Components
fieldLayouts:
  b319e26a-e400-4e30-a7ec-ee0e14c35f27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b17e3fa4-b66f-42e0-89d3-cc3f7de93740 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 349052f1-a2eb-4d43-8bcb-f1cde2443506
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e0a369a-d9c6-4dbc-b572-9575a85b1dac # Short Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0e1f833-f300-4154-9c2b-86b8599d0667
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac60f42c-c1aa-41be-a488-4d28c6b6ec1f # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e8ae1b3-1f35-4c21-834f-9c8c316046dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6917776a-74ce-4fff-a011-a1c66b327c81
        userCondition: null
fields:
  8e0a369a-d9c6-4dbc-b572-9575a85b1dac: # Short Text
    columnSuffix: iqnkxidc
    contentColumnType: text
    fieldGroup: null
    handle: shortText
    instructions: null
    name: 'Short Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 500
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ac60f42c-c1aa-41be-a488-4d28c6b6ec1f: # Hero Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroImage
    instructions: null
    name: 'Hero Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:e52503d0-9bc0-4f71-bcdc-23e8f53a1e58' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e52503d0-9bc0-4f71-bcdc-23e8f53a1e58' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:e52503d0-9bc0-4f71-bcdc-23e8f53a1e58' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b17e3fa4-b66f-42e0-89d3-cc3f7de93740: # Heading
    columnSuffix: itadloce
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: 500
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hero
name: Hero
sortOrder: 1
