fieldLayouts:
  c655fdfd-55f6-41be-abbd-26d1eb6f5750:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a85091ee-3357-4ca8-be54-be64d7ae0673
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cb1883a-4c9d-4d32-9386-210a71fbe719 # Components
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e136735-1722-4264-95a8-afaa303038ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 397229b9-131d-428a-ad85-5ee5c9911d13
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: d867311c-10fa-4995-a2dd-9187d62d1f2a # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
