dateModified: 1723089018
email:
  fromEmail: sample@email.com
  fromName: 'Imagic Craft Site'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: uploads
    type: craft\fs\Local
    url: uploads
meta:
  __names__:
    1cb1883a-4c9d-4d32-9386-210a71fbe719: Components # Components
    2d1f5733-3df1-4570-a0ed-af51908a8a2b: 'Imagic Craft Site' # Imagic Craft Site
    7d7aec54-3b8c-4f3c-a18c-35883a7ee404: Common # Common
    8e0a369a-d9c6-4dbc-b572-9575a85b1dac: 'Short Text' # Short Text
    8eb5908a-32aa-46ea-a516-6e2257cf2fed: 'Imagic Craft Site' # Imagic Craft Site
    22e61d75-7f6d-4940-a410-3021805e00ba: Home # Home
    ab249b3f-99eb-4e73-9dcf-1c98e3914240: Heading # Heading
    ac60f42c-c1aa-41be-a488-4d28c6b6ec1f: 'Hero Image' # Hero Image
    acaeab4a-c75b-4a4b-8b0d-ce635d649fb2: 'Image Carousel' # Image Carousel
    b1f2fd65-ae22-447c-9e55-00ee1d289053: 'Short Description' # Short Description
    b17e3fa4-b66f-42e0-89d3-cc3f7de93740: Heading # Heading
    d6dd6e70-c071-45bb-867c-42d874d4b3e2: Images # Images
    d867311c-10fa-4995-a2dd-9187d62d1f2a: Home # Home
    dfe63ba6-923e-4be5-91f3-74717e874145: Hero # Hero
    e52503d0-9bc0-4f71-bcdc-23e8f53a1e58: Images # Images
system:
  edition: solo
  live: true
  name: 'Imagic Craft Site'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
